#ifndef CLIENT_PROTOCOL_H
#define CLIENT_PROTOCOL_H

#define MAX_USER_USERNAME_SIZE	100
#define MAX_USER_PASSWORD_SIZE	100

// Macro per il text protocol
//requests
#define REGISTER_PROTOCOL_MESSAGE 									"REGISTER"
#define LOGIN_PROTOCOL_MESSAGE 										"LOGIN"
#define GET_FILMS_PROTOCOL_MESSAGE  								"GET_FILMS"
#define RENT_FILM_PROTOCOL_MESSAGE  								"RENT_FILM"
#define RETURN_RENTED_FILM_PROTOCOL_MESSAGE							"RETURN_RENTED_FILM"
#define GET_MAX_RENTED_FILMS_PROTOCOL_MESSAGE						"GET_MAX_RENTED_FILMS"
#define GET_USER_EXIRED_FILMS_NO_DUE_DATE_PROTOCOL_MESSAGE			"GET_USER_EXPIRED_FILMS_NO_DUE_DATE" //DA FARE											
#define SHOPKEEPER_CHANGE_MAX_RENTED_FILMS_PROTOCOL_MESSAGE			"SHOPKEEPER_CHANGE_MAX_RENTED_FILMS"
#define SHOPKEEPER_NOTIFY_EXPIRED_FILMS_PROTOCOL_MESSAGE			"SHOPKEEPER_NOTIFY_EXPIRED_FILMS"// DA FARE

//response
#define SUCCESS_REGISTER										"SUCCESS_REGISTER"
#define SUCCESS_LOGIN											"SUCCESS_LOGIN"
#define SUCCESS_GET_FILMS										"SUCCESS_GET_FILMS"
#define SUCCESS_RENT_FILM										"SUCCESS_RENT_FILM"
#define SUCCESS_RETURN_RENTED_FILM								"SUCCESS_RETURN_RENTEND_FILM"
#define SUCCESS_GET_MAX_RENTED_FILMS							"SUCCESS_GET_MAX_RENTED_FILMS"
#define SUCCESS_GET_USER_EXIRED_FILMS_NO_DUE_DATE				"SUCCESS_GET_USER_EXPIRED_FILMS_NO_DUE_DATE"
#define SUCCESS_SHOPKEEPER_CHANGE_MAX_RENTED_FILMS				"SUCCESS_SHOPKEEPER_CHANGE_MAX_RENTED_FILMS"
#define SUCCESS_SHOPKEEPER_NOTIFY_EXPIRED_FILMS					"SUCCESS_SHOPKEEPER_NOTIFY_EXPIRED_FILMS"

#define FAILED_USER_ALREDY_EXISTS								"FAILED_USER_ALREADY_EXISTS"
#define FAILED_USER_DOESNT_EXISTS								"FAILED_USER_DOESNT_EXISTS"
#define FAILED_USER_BAD_CREDENTIALS								"FAILED_USER_BAD_CREDENTIALS"

#define FAILED_RENT_FILM_MAX_ALLOWED							"FAILED_RENT_FILM_MAX_ALLOWED"
#define FAILED_RENT_FILM_NO_AVAILABLE_COPY						"FAILED_RENT_FILM_NO_AVAILABLE_COPY"
#define FAILED_RENT_ALREADY_EXISTS								"FAILED_RENT_ALREADY_EXISTS"

#define FAILED_RETURN_RENTED_FILM_NO_AVIABLE_RENTED_OUT			"FAILED_RETURN_RENTED_FILM_NO_AVIABLE_RENTED_OUT"

#define FAILED_SHOPKEEPER_CHANGE_MAX_RENTED_FILMS_ROLE		 	"FAILED_SHOPKEEPER_CHANGE_MAX_RENTED_FILMS_ROLE"
#define FAILED_SHOPKEEPER_CHANGE_MAX_RENTED_FILMS_USER_EXEEDED 	"FAILED_SHOPKEEPER_CHANGE_MAX_RENTED_FILMS_USER_EXEEDED"

#define FAILED_SHOPKEEPER_NOTIFY_EXPIRED_FILMS_ROLE			 	"FAILED_SHOPKEEPER_NOTIFY_EXPIRED_FILMS_ROLE"

#define PROTOCOL_MESSAGE_MAX_SIZE 								100

typedef struct user_t {
	int id;
	char username[MAX_USER_USERNAME_SIZE];
	char password[MAX_USER_PASSWORD_SIZE];
} user_t;

// Global variables
extern unsigned int user_id;
extern user_t user;

// Function prototypes
void get_user_id(int client_socket);
int check_server_response(int client_socket);

#endif
